AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - '.git/**/*'
  - '*.csv'
  - '*.json'
  - '*.yml'

#
# Layout
#

# Match existing layout
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

# Match existing layout
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block

Layout/ClassStructure:
  Enabled: true

Layout/ConditionPosition:
  Enabled: true

# Match existing layout
Layout/DotPosition:
  AutoCorrect: true
  EnforcedStyle: trailing

Layout/EndAlignment:
  AutoCorrect: true

# Prevent accidental windows line endings
Layout/EndOfLine:
  EnforcedStyle: lf

# ForceEqualSignAlignment is broken, see https://github.com/rubocop-hq/rubocop/pull/5696
Layout/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: true
  AutoCorrect: true

# Pick one
Layout/IndentHeredoc:
  EnforcedStyle: squiggly

Layout/RescueEnsureAlignment:
  AutoCorrect: true

## Rubocop cannot yet see beyond one line above or below, when aligning =
Layout/SpaceAroundOperators:
  AllowForAlignment: true
  AutoCorrect: true

# Match existing layout
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

## Files must end with a blank line
Layout/TrailingBlankLines:
  EnforcedStyle: final_newline

Metrics/AbcSize:
  Max: 80

# Support long block lengths for tests
Metrics/BlockLength:
  Exclude:
  - '**/test/**/*'

Metrics/ClassLength:
  Max: 250
  Exclude:
  - '**/test/**/*'

Metrics/LineLength:
  Max: 128
  Exclude:
  - '**/test/**/*'
  - lib/cli.rb

Metrics/MethodLength:
  Max: 250

# Soften limits
Metrics/ModuleLength:
  Max: 250

Metrics/ParameterLists:
  CountKeywordArgs: false

# Missing top-level module documentation comment
Style/Documentation:
  Enabled: false

# One line methods
Style/EmptyMethod:
  EnforcedStyle: expanded

# Ruby 3 compatibility feature
Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  AutoCorrect: true

# Incorrectly changes job.fail to job.raise
Style/SignalException:
  Enabled: false

# Since English may not be loaded, cannot force its use.
Style/SpecialGlobalVars:
  Enabled: false

# Make it easier for developers to move between Ruby and Elixir.
Style/StringLiterals:
  EnforcedStyle: double_quotes
